### PR TITLE
spec typo ES265K -> ES256K

### PR DESCRIPTION
**Pull request by gobengo**
so interop is not hindered while people search for a secp265k1 curve 
😂

### CODE REVIEW

**Comment by csuwildcat** [comment]
You'll need to edit the markdown source, not the rendered HTML.

**Comment by gobengo** [comment]
@csuwildcat Thanks for pointing that out. Updated my branch. (the html file changes are now more numerous, but strictly generated via `npm run render`, I think because no one had committed an update rendering recently)

**Comment by TallTed** [comment]
@gobengo -- Your PR still includes the HTML doc, which includes a number of changes that should not be made (e.g., `<div id="todo-36"` -> `<div id="todo-1"` ***and*** `<div id="note-15"` -> `<div id="note-1"`, where each `div` entity should have a unique value for their `id` attribute).  You will probably find it easiest to start afresh with a clean clone/fork where you can tweak the MD doc, and skip the HTML regeneration (which I *think* will be handled by other tooling).

**Comment by gobengo** [comment]
@TallTed I looked at the [history](https://github.com/decentralized-identity/identity-hub/commits/main/spec/index.html) for the spec/index.html file, and it seems to be frequently re-rendered and committed alongside changes to spec.md. [example commit](https://github.com/decentralized-identity/identity-hub/commit/df1fcaa4e10d2b42caed047e4e1172f1fb88cd42#diff-97efdc0e30285fae4d5cb7cc4a510dbaa7c33f4e56d4216dcde109ad2cdef15f). Notably, that commit also includes nondeterministic generation of the HTML element ids, which I'd guess is 'normal behavior' for the [spec-up](https://github.com/decentralized-identity/spec-up) renderer.

Since @csuwildcat has made almost all the commits to these files, I will follow his direction as to whether this commit should modify spec/index.html or only the md

**Comment by csuwildcat** [comment]
@gobengo you don't need to worry about the HTML, it will be overwritten by the rendered output from the GitHub Action that uses the MD as source.

**Review by csuwildcat — APPROVED** [review]

**Comment by gobengo** [comment]
@csuwildcat got it, I will exclude it from future commits.

**Pull request merged**
